### ISSUE TITLE
Have the trouble with process big size file

### ISSUE THREAD

**Issue by marss-hub** [olegbarabanov/tinyibp#2]
Hi! I used tinyibp to process my images and had a problem when uploaded an img with size 6300 x 8910 px.

operating system: Windows 10 64-bit
the version of the browser: Opera 74.0.3911.160
msg in browser`s console: asyncToGenerator.js:6 Uncaught (in promise) DOMException: The source image cannot be decoded.

I hope it is possible to fix this problem. 
Best regards.

**Comment by olegbarabanov** [comment]
Hi @marss-hub !

Currently, initial support for large image processing has been added. See commit 1a12e87e26318cb0e45b21adb4acec429505b23a
Unfortunaly, it's still unstable and it does not have full SVG support.

Thank you.

**Comment by marss-hub** [comment]
Thank you! it works with large files now! And it great for me.
